* Intro 
You won't miss a thing in this comprehensive tour! 
Join us to visit all of the top world-renowned attractions in Beijing 

Being the capital of the People's Republic of China, Beijing is the
nation's political, economic, and cultural center. Located in north
China, close to the port city of Tianjin and partially surrounded by
Hebei Province, it also serves as the most important transportation
hub and port of entry.

As one of the oldeset cities in China, Beijing has been the centre
stage of politics throughout its long history and consequently there
is an unparalleled wealth of discovery and records to delight and
intrigue the most curious travelers as they explore the city's
glorious past and exciting modern development. Now it has become one
of the most popular travel destinations in the world, attracting
approximately 140 million Chinese tourists and 4.4 million
international visitors in a year.
* Landing in Beijing 
* Day 1 
** Pick up from your hotel at 8:30 AM.
*** Tiananmen Square - Stroll around this public square
*** Forbidden City - Delve into this "City"
*** Jing Shan Park - Climb to the mountain top for a bird's eye view
** Lunch: Enjoy Chinese Cuisine at a local restaurant
*** Hutongs
* Day 2 
** Pick up at 8:00 AM 
*** Ming Tombs & Sacred Way: Scenic drive to the Sacred Way and the Ming Tombs. Walk to the Chang Ling Tomb, the largest of the Ming Tombs.  
** Lunch: Enjoy Chinese Cuisine. at a local restaurant 
*** Great Wall of Mutianyu - Take once-in-a life-time hike (2 to 3 hours). Take memorable pictures!
* Day 3 
** Pick up at 9:00 AM 
*** Temple of Heaven: Largest group of Temple Buildings in China & largest Heaven-Worshiping structure in the world.
*** Summer Palace: Best-preserved Imperial Garden in China. Take a leisurely stroll, a boat ride. Enjoy the beautiful vistas.
** Lunch: Chinese Cuisine at a local restaurant
*** Lama Temple: This nearly 300-year old building is a temple & a working monastery with a unique and magnificent architecture
* Return 
* More info 
** Transportation 
*** Air transport via Qantas 
*** Air-conditioned van/Car with professional driver 
*** Flight duration 1hr 20mins Melb-Syd + 11hrs 45mins Syd-Beij 
** Price 
*** US$3999 (airfare + all entries + all meals included) 
** Ducuments 
*** See brochure 
